### ISSUE TITLE
无法下载MobileMouse.exe，404文件找不到

### ISSUE THREAD

**Issue by salman-apk** [imengyu/MobileMouse#1]

**Comment by imengyu** [comment]
疏忽了(⊙x⊙;)gitignore设置错了。我把缺的文件也补上来了

**Comment by salman-apk** [comment]
兄弟，你能不能完成  **_Autocalc_**  项目，我爱你的计算器

**Comment by imengyu** [comment]
可以，不过最近我可能没有时间，我需要另外找时间。你大致需要什么样的功能，或者要达到什么样的目标

**Comment by salman-apk** [comment]
请给我一些时间，我会考虑所有可能使**_AutoCalc_**成为出色计算器的良好功能，我会回复您的电子邮件！

**Comment by salman-apk** [comment]
您应该添加

- 暗/亮模式
- 语音命令功能
- 计算器小部件
- 添加广告或应用内购买或仅捐赠支持
- 增强用户界面
- 修复了一些错误

我爱您的计算器，如果您要添加这些功能，则计算器将变得超级。
提前致谢
